### ISSUE TITLE
Assertion error while reading item list

### ISSUE THREAD

**Issue by Parakoopa** [SkyTemple/skytemple-files#22]
`Traceback (most recent call last):
  File "skytemple/core/controller_loader.py", line 32, in load_controller
  File "skytemple/module/dungeon/controller/floor.py", line 99, in __init__
  File "skytemple/module/dungeon/module.py", line 150, in get_mappa_floor
  File "skytemple/module/dungeon/module.py", line 136, in get_mappa
  File "skytemple/core/rom_project.py", line 182, in open_file_in_rom
  File "site-packages/skytemple_files/dungeon_data/mappa_bin/handler.py", line 35, in deserialize
  File "site-packages/skytemple_files/container/sir0/handler.py", line 57, in unwrap_obj
  File "site-packages/skytemple_files/dungeon_data/mappa_bin/model.py", line 67, in sir0_unwrap
  File "site-packages/skytemple_files/dungeon_data/mappa_bin/model.py", line 77, in _read_floor_list
  File "site-packages/skytemple_files/dungeon_data/mappa_bin/model.py", line 90, in _read_floors
  File "site-packages/skytemple_files/dungeon_data/mappa_bin/floor.py", line 99, in from_mappa
  File "site-packages/skytemple_files/dungeon_data/mappa_bin/floor.py", line 138, in _from_cache
  File "site-packages/skytemple_files/dungeon_data/mappa_bin/floor.py", line 102, in <lambda>
  File "site-packages/skytemple_files/dungeon_data/mappa_bin/item_list.py", line 123, in from_mappa
AssertionError`

---
Beep, boop, I'm [a bot](https://github.com/Parakoopa/IssueBot)! This issue was created by `@Maestroke` in `#skytemple-tester`.

**Comment by Parakoopa** [comment]
The mappa_s.bin file that caused the issue had small errors in the item list.
