### ISSUE TITLE
Trap/Item sprites not found in JP ROM

### ISSUE THREAD

**Issue by Adex-8x** [SkyTemple/skytemple-files#412]
Whenever SkyTemple attempts to load an item sprite for a JP ROM, be it when viewing an item in the _Items_ tab or viewing _Dungeon Graphics -> Items_, the application freezes and must be force quit.
This also seems to cause a similar issue when attempting to edit a dungeon floor:
<img width="584" alt="Screenshot 2023-09-06 at 9 01 08 AM" src="https://github.com/SkyTemple/skytemple-files/assets/91418697/84bf547e-d583-49a5-b2ab-1a392575720a">
From `skytemple.log`:
```
2023-09-06 08:13:58,036 - skytemple.core.sprite_provider - WARNING - Error loading an trap sprite for 20.
Traceback (most recent call last):
  File "core/sprite_provider.py", line 453, in _load_trap__impl
  File "skytemple_files/container/dungeon_bin/model.py", line 45, in get
KeyError: 'File traps.trp.img not found.'
2023-09-06 08:13:58,043 - skytemple.core.sprite_provider - WARNING - Error loading an trap sprite for 21.
Traceback (most recent call last):
  File "core/sprite_provider.py", line 453, in _load_trap__impl
  File "skytemple_files/container/dungeon_bin/model.py", line 45, in get
KeyError: 'File traps.trp.img not found.'
2023-09-06 08:13:58,045 - skytemple.core.sprite_provider - WARNING - Error loading an trap sprite for 22.
Traceback (most recent call last):
  File "core/sprite_provider.py", line 453, in _load_trap__impl
  File "skytemple_files/container/dungeon_bin/model.py", line 45, in get
KeyError: 'File traps.trp.img not found.'
2023-09-06 08:13:58,047 - skytemple.core.sprite_provider - WARNING - Error loading an trap sprite for 23.
Traceback (most recent call last):
  File "core/sprite_provider.py", line 453, in _load_trap__impl
  File "skytemple_files/container/dungeon_bin/model.py", line 45, in get
KeyError: 'File traps.trp.img not found.'
2023-09-06 08:13:58,049 - skytemple.core.sprite_provider - WARNING - Error loading an trap sprite for 24.
Traceback (most recent call last):
  File "core/sprite_provider.py", line 453, in _load_trap__impl
  File "skytemple_files/container/dungeon_bin/model.py", line 45, in get
KeyError: 'File traps.trp.img not found.'
```

**Comment by theCapypara** [comment]
@Laioxy That seems to be the case. I opened #415 to track dungeon.bin.
